### ISSUE TITLE
Issues in 3. Feature Engineering

### ISSUE THREAD

**Issue by syedshazli** [EthanFalcao/WPI-IA-Portfolio-Optimization-and-Risk-Analysis#5]
3. Feature Engineering.ipynb consists of cryptocurrency related topics and includes crypto such as ADA, BTC, AVAX, etc. in the data rather than the DOW-30. Should aim to fix before June 1.

![image](https://github.com/EthanFalcao/WPI-IA-Portfolio-Optimization-and-Risk-Analysis/assets/146783525/a2f03915-7f3f-48cc-b21b-b82eef410655)

**Comment by EthanFalcao** [comment]
ya, i was planning on removing the crypto stuff form, will finish do before june 1

**Comment by syedshazli** [comment]
sounds good I'll try to revamp stuff in 2. EDA cuz I think theres still some crypto stuff that I can ctrl + f   find & replace
